src/parser.rs

First PR to this repo! :smile: 
If you could make a list of tasks that need to be done (for example, adding new parsers) I would be glad to help!

Fix error in documentation

---

src/char.rs

Parser creating functions should always be specialized same as when they implement Parser so that they cannot create values which arent parsers.

Hide the digit and space parsers behind a newtype and specialize char parsers

---

src/lib.rs

No features. Just keeping the compiler quiet for its oncoming changes.

silence unstable and feature warnings

---

src/lib.rs

Adds collections and slice_patterns features.

Update for latest rustc nightly

---

src/combinator.rs
src/lib.rs

hi,
Please consider merging look_ahead combinator.

Add look_ahead combinator

---

src/combinator.rs

Improve the documentation for `or` and `choice` with better examples

---

src/char.rs
src/combinator.rs
src/primitives.rs

...in some instances where it's misspelled as 'characther'.

Fix 'character' typos

---

benches/http-requests.txt
benches/http.rs
src/combinator.rs

@m4rw3r This is based on the http-parser you implemented in combine a while back. Is it ok if I include this in the repo?

test: Add a benchmark for a http request parser 

---

src/byte.rs
src/char.rs
src/combinator.rs
src/lib.rs
src/primitives.rs
src/range.rs

Fix a couple of broken code examples, reword some descriptions and add a
lot of full-stops and links.

Improve documentation

---

src/primitives.rs

Add more detail to `parse_{stream,stream_consumed,lazy}`
Also fix some spelling and a broken link

Add more detailed documentation to `Parser` trait

---

src/range.rs

The `take_until(r)` parser parses until the range `r` is found, at which
point all input up to (but not including) `r` will be returned. If `r`
is not found, an error will be returned.

Add the take_until range parser

---

benches/http.rs
benches/json.rs
benches/mp4.rs
src/byte.rs
src/char.rs
src/combinator.rs
src/lib.rs
src/primitives.rs
src/range.rs
tests/buffered_stream.rs
tests/date.rs
tests/ini.rs

Fixed the conflicts of #96 (@chengsun  Sorry for dropping the ball on it. Got it mixed up with #95 and forgot it did not need any breaking changes.)
Should have a potential fix of #95 fairly soon as well though there are some edge cases that are tricky to encode. 
Closes #96

fix: Fixes to `try` and `expected`

---

src/combinator.rs

`recognize` can be used to recognize what a parser consumed and return the tokens accumulated into a `FromIterator`. A range based version of this is coming in 3.0

feat: Add the recognize parser

---

benches/http.rs
src/combinator.rs

This associates the output of a parser diretly to the struct which can make some parser easier to read

feat: Add a macro to parse values directly into structs

---

src/regex.rs

fix(doc): regex find consumes input until the end of the first match

---

examples/date.rs
examples/ini.rs
examples/readme.rs
src/combinator.rs
src/regex.rs
travis.sh

docs: Move the examples into the examples directory

---

src/range.rs

Only 3.x and zero-copy for now.
Bikeshedding on the name is welcome :smile:

feat: add new range parser, returning (range, value)

---

src/combinator.rs

fix: sep_end_by1 should not be able to skip parsing elements

---

src/parser/choice.rs
src/parser/sequence.rs

feat: Let single element tuples work as sequence and choice parsers

---

.travis.yml

Workkaround for https://github.com/xd009642/tarpaulin/issues/77

chore: Require sudo on travis so tarpaulin works

---

CHANGELOG.md
Cargo.toml
src/parser/byte.rs
src/parser/combinator.rs
src/parser/repeat.rs
src/stream/mod.rs
tests/async.rs

cc @cschneid https://github.com/Marwes/combine/commit/7b03b596a58e4cdbe84d6008e277f0cc57394fae
cc @HolgerPeters https://github.com/Marwes/combine/commit/b1cb0668cc13df3a2f1b6cc35f221089d0279579

Version 3.1.0

---

benches/json.rs
examples/async.rs
examples/date.rs
examples/ini.rs
travis.sh

Rewrite all examples to use `impl Parser` instead of `parser!`

---

benches/http.rs
benches/json.rs
benches/mp4.rs
examples/async.rs
examples/date.rs
examples/ini.rs
examples/number.rs
examples/readme.rs
rustfmt.toml
src/lib.rs
src/parser/byte.rs
src/parser/char.rs
src/parser/choice.rs
src/parser/combinator.rs
src/parser/error.rs
src/parser/function.rs
src/parser/item.rs
src/parser/mod.rs
src/parser/range.rs
src/parser/regex.rs
src/parser/sequence.rs
src/stream/easy.rs
src/stream/mod.rs
src/stream/state.rs
tests/buffered_stream.rs
tests/parser.rs
travis.sh

 doc: Use impl Parser in the src/lib.rs example 

---

CHANGELOG.md
Cargo.toml
release.toml
src/lib.rs
src/parser/mod.rs
tests/parser.rs

fix: Forward the partial mode through the parser! macro correctly

---

src/lib.rs
src/parser/combinator.rs
src/parser/item.rs
src/parser/range.rs
src/stream/easy.rs
src/stream/mod.rs
tests/async.rs

Add some more parser combinators

---

src/error.rs
src/lib.rs
src/parser/byte.rs
src/parser/char.rs
src/parser/choice.rs
src/parser/combinator.rs
src/parser/error.rs
src/parser/function.rs
src/parser/item.rs
src/parser/mod.rs
src/parser/range.rs
src/parser/regex.rs
src/parser/repeat.rs
src/parser/sequence.rs
src/stream/easy.rs
tests/parser.rs

fix: Report more expected information from nested sequence parsers

---

CHANGELOG.md
Cargo.toml
src/parser/combinator.rs

feat: Add the factory parser

---

CHANGELOG.md
Cargo.toml
src/parser/choice.rs
tests/parser.rs

fix: Add all errors of nested choice parsers

---

benches/http.rs
benches/json.rs
benches/mp4.rs
examples/async.rs
examples/date.rs
examples/ini.rs
src/error.rs
src/lib.rs
src/parser/byte.rs
src/parser/char.rs
src/parser/choice.rs
src/parser/function.rs
src/parser/repeat.rs
src/stream/mod.rs
tests/async.rs
tests/parser.rs

Fixes #216 by reusing the count_min_max implementation which had a similar fix.

Reset count state after extending the iterator 

---

src/parser/combinator.rs
tests/parser.rs

fix: not_followed_by should fail on empty successful parses

---

benches/json.rs
src/error.rs
src/parser/byte.rs
src/parser/combinator.rs
src/parser/error.rs
src/parser/function.rs
src/parser/item.rs
src/parser/mod.rs
src/parser/range.rs
src/parser/regex.rs
src/parser/repeat.rs
src/stream/easy.rs
travis.sh

feat: Allow fmt::Display be used to specify errors in combinators

---

src/parser/choice.rs
src/parser/combinator.rs
src/parser/error.rs
src/parser/mod.rs
src/parser/sequence.rs
src/stream/easy.rs

Some documentation links were wrong

fix links in documentation

---

src/stream/position.rs

`ReadStream` needs an additional generic parameter for `Position`.

implement support for SourcePosition to work on u8 streams

---

src/parser/mod.rs
src/parser/sequence.rs

`ThenRef` is similar to `Then`, except it passes a reference to the input value rather than passing ownership. Then, it combines the input value with the output value of the closure in a 2-tuple.
This makes it more straightforward to have conditional parsing based on parsed values which are needed further down the combinator chain.

feat: Implement then_ref/ThenRef combinator

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/stream/buf_reader.rs
src/stream/mod.rs
tests/async.rs

https://github.com/mitsuhiko/redis-rs/issues/358

fix: Make the decode macros work for redis

---

benches/http.rs
benches/json.rs
examples/date.rs
examples/ini.rs
examples/number.rs
src/error.rs
src/lib.rs
src/parser/byte.rs
src/parser/mod.rs
src/parser/repeat.rs
src/parser/token.rs
src/stream/buffered.rs
src/stream/easy.rs
src/stream/mod.rs
src/stream/position.rs
tests/buffered_stream.rs
tests/support/mod.rs

Including one that leaks out of the decode macros, causing errors in redis-rs

Fix some clippy nits

---

benches/json.rs
examples/ini.rs
examples/number.rs
src/error.rs
src/lib.rs
src/parser/choice.rs
src/parser/combinator.rs
src/parser/mod.rs
src/parser/range.rs
src/parser/repeat.rs
src/parser/token.rs
src/stream/buffered.rs
src/stream/easy.rs
src/stream/mod.rs
tests/buffered_stream.rs

What's missing is running these on CI, which I refrained from doing in this PR to not conflate things.

Apply cargo clippy and cargo fmt

---

Cargo.lock
Cargo.toml
src/error.rs
src/parser/combinator.rs
src/parser/error.rs
src/parser/mod.rs
src/stream/decoder.rs
src/stream/easy.rs
src/stream/mod.rs
src/stream/span.rs

cc https://github.com/Marwes/combine/issues/304

feat: Add a spanned combinator

---

src/parser/range.rs
travis.sh

feat: Add a length_prefix combinator

---

README.md
src/stream/mod.rs
tests/async.rs

Hi, I am a fan of your cool library. I translated some wiki docs into Japanese. Can I publish it as public? And If you’d like, can I add a link in README.md?

Translate wiki docs into Japanese, and add a link to README
