src/lib.rs
src/parser.rs
src/primitives.rs

Fixes #4. No test is added for the bug since it is no longer possible to write the bug using the new types.
See respective commits for comments on exact changes.

Redesigned the Consumed enum to be less prone to errors

---

src/char.rs
src/combinator.rs
src/lib.rs
src/primitives.rs

Most of the error messages are &'static str which means using a String as the message type is usually a waste allocation.
The parser API should still be relatively unaware of this change since the only change was String -> T where T: IntoCow

Changed the internal Error enum to use CowString<'static>

---

src/char.rs
src/combinator.rs
src/lib.rs

Added the expected combinator which is the parallel to `<?>` in parsec. Using this combinator I added some more descriptive error messages to the char parsers.

Improved the error messages created by the char parsers

---

src/char.rs

Pretty sure the `lower()` parser parses a lowercase letter. :)

Fix incorrect documentation for `lower`

---

src/combinator.rs
src/primitives.rs

Intended to solve #22. I think the addition of the Other variant is an useful regardless but I am a bit vary of the `and_then` function since there is some overlap with then `then` function and I could also think of a third function which would have a signature like:
```rust
fn and_then<F, O>(self, f: F) -> AndThen<Self, F>
where F: FnMut(Self::Input, Self::Output) -> ParseResult<O, Self::Input>;
```

Add and_then combinator

---

src/primitives.rs

When using parser-combinators with channels and threads, it is useful to be
able to send errors.  This changes Error so that it satisfies Send.

Make Error satisfy Send

---

benches/json.rs
src/char.rs
src/combinator.rs
src/lib.rs
src/primitives.rs

This is a mostly complete PR of how I think parsing can be made generic in the position. I will leave it as a PR until I can finish documenting it and maybe bring the performance up to the same levels as before.
* any_char, satisfy and char works on any type of stream instead of only char streams (called any, satisfy and token respectively)
* Implementing streams over custom types can use different types for representing and updating positions see: [#L29-L38](https://github.com/Marwes/parser-combinators/blob/8a7d5651c1c5511444b0b353d5b9a4121fbc16f8/src/primitives.rs#L29-L38)   [#L456-L466](https://github.com/Marwes/parser-combinators/blob/8a7d5651c1c5511444b0b353d5b9a4121fbc16f8/src/primitives.rs#L456-L466)
* Being more generic makes it harder for rustc to infer types
* Currently there is …

Added custom positioning

---

benches/json.rs
src/char.rs
src/combinator.rs
src/lib.rs
src/primitives.rs

Parsers such as `choice` and `.or` can result in the creation of several errors before they find the correct parser. The `parse_ok` and `add_error` methods are added to allow parsers to avoid allocating a vector to store the error in some cases. Instead the parser promises that it can generate the error at a later point if asked for it through the `add_error` method.
This gives a 30% speedup on the json parser benchmark but since it mostly contained strings for values it was already optimized to generate less by placing the string parser first in the `.or` chain it can be expected to see larger improvements for more balanced code.
(placing the string parser last showed a ~90% improvement)

Add an extra method to Parser which does not generate empty parse errors

---

benches/json.rs
src/char.rs
src/combinator.rs
src/lib.rs
src/primitives.rs

This is a breaking change as it changes the type signature for errors.
Info and Error has an extra parameter where they can specify a range error. ParseError now takes the stream type instead of token type as its parameter. The idea is that ParseError will later be made into type alias when type aliases allow bounds on their parameters. That change should be possible to make without a breaking change once its supported.
```
type ParseError<S: Stream> = ParseError2<S::Item, S::Range>;
```

Adds support for range errors in preparation for RangeStream

---

src/combinator.rs
src/primitives.rs

As was pointed out to me by @m4rw3r `&[T]` streams are usually on `&[u8]` or other types `T` which are copyable. This would allow the Item type of such streams to be `T` rather than `&T` but has the downside that you can use `&[T]` where `T != Copy`. A newtype could be added which wraps such `&[T]` slices allowing for `&T` items again.
Alternatives:
* Introduce a newtype which can be used to wrap slices with T: Copy instead.
```rust
#[derive(Debug, PartialEq, Clone)]
struct CopySlice<'a, T: 'a>(&'a [T]);
impl <'a, T: Positioner + Copy + 'a> Stream for CopySlice<'a, T> {
type Item = T;
type Range = &'a [T];
fn uncons(self) -> Result<(T, CopySlice<'a, T>), Error<T, CopySlice<'a, T>> {
...
}
}
```
I don't have much of any opinion either way but it needs to be decided before 1.0. Wrapping the …

Make T: Copy for &[T] streams

---

README.md

The README still mentions 1.0 as if it were a future release in the context of semantic versioning.

Don't speak about instability anymore

---

.travis.yml
Cargo.toml
README.md
src/combinator.rs
src/primitives.rs

Ranged streams are streams which in addition to allowing taking elements one by one also are able to take an entire range of elements efficiently. For example the stream `&str`  can be split into two different slices. This should give a large performance boost to streams which uses it as they can avoid allocating every time multiple tokens are needed and instead just use the data in the stream itself.
This PR is a breaking change since it changes the `ParseError<T = Stream::Item>` to `ParseError<S: Stream>` so it needs to be merged before 1.0 (I had hoped not to break anything after 1.0- beta but this is only minor breaking change and only if you used some types directly from the primitives module). I might lift that breaking change out and merge it separately, allowing 1.0 to be released …

Add ranged streams

---

src/lib.rs

…cies
The definition of the parsers doesn't depend on the input string in any way. In particular, merely building the parsers doesn't cause a parse to take place. This comment makes this clear by defining the input string only after the parsers have been defined.

Move input definition in code example to better reflect data dependencies

---

src/combinator.rs
src/lib.rs

The function `env_parser` works in the same way as the `parser` function but allows the construction of parsers from `fn (Env, State<I>) -> ParseResult<O, I>`. An implementation of this has been in both `combine-language` and `embed_lang` where it has been very useful by allowing parsers to share some common environment while still allowing each parser to be self contained to a single function.

Add EnvParser (env_parser)

---

src/combinator.rs
src/primitives.rs
src/range.rs

Together, these commits address the cases I asked about in #74 and #75.  With these, `SliceStream` consumers can use `token()`; and consumers who want a `T` item type can parse non-`Copy` tokens.

Prefer Clone to Copy. Fixes #74.

---

src/lib.rs
src/primitives.rs

It's possible to `map_err_range` for `ParseResult<>` too, but it's
awkward because the output type needs to be a compatible `StreamOnce`.
As suggested in
https://github.com/Marwes/combine/issues/86#issuecomment-280487165,
it's probably best to either change the parse result type entirely, or
wait for https://github.com/rust-lang/rust/issues/21903.
This at least helps consumers convert `ParseError<>` into something
that can implement `std::fmt::Display`.

Add map functions for Error<> and Info<> ranges. (#86)

---

benches/json.rs

Fix 2 bugs in `benches/json.rs`.
- Remove leading new line in json string literal causes parse error.
- Fix wrong evaluation about number between 0.0 and 1.0 in `number_()`.

Fix bugs in benches/json.rs

---

src/combinator.rs

Fix to `message` issue we were discussing on gitter earlier.
Add a unit test checking for the issue.

Fix `Message` so it always adds its message

---

Cargo.toml
src/lib.rs
src/primitives.rs
tests/buffered_stream.rs

this way it shows up in `ReadStream`'s documentation as an associated
method and users are less confused as to how to build a `ReadStream`
i know this breaks API and would therefore only be mergeable for some later release (if you want it at all), but i thought this was the quickest way to suggest this change (quicker/better than to write a lengthy bug report detailing what i mean, at least).

move from_read into ReadStream impl block

---

.travis.yml
src/byte.rs
src/char.rs
src/lib.rs

Uses https://github.com/xd009642/tarpaulin to provide code coverage to coveralls. Currently doc tests aren't taken into account which makes coverage fairly low but at least it works again!
Closes #94

chore: Add code coverage via tarpaulin

---

src/primitives.rs

While reading the documentation I noticed some broken links on `https://docs.rs/combine/2.4.0/combine/primitives/trait.Parser.html`. This PR fixes these broken links.
For completeness I used [linkchecker](https://wummel.github.io/linkchecker/) on https://docs.rs/combine/2.4.0/combine/ to verify that these were the only broken links:
```
LinkChecker 9.3              Copyright (C) 2000-2014 Bastian Kleineidam
LinkChecker comes with ABSOLUTELY NO WARRANTY!
This is free software, and you are welcome to redistribute it
under certain conditions. Look at the file `LICENSE' within this
distribution.
Get the newest version at http://wummel.github.io/linkchecker/
Write comments and bugs to https://github.com/wummel/linkchecker/issues
Support this project at …
```

docs: Fix some broken links

---

benches/json.rs
src/char.rs
src/combinator.rs
src/lib.rs
tests/date.rs
tests/ini.rs

While it has a slightly weird syntax to work around some ambiguity problems this should provide a defacto way to implement reusable parsers.
Fixes #70

feat: Add a macro for declaring parsers

---

.travis.yml
CHANGELOG.md
Cargo.toml
README.md
benches/http.rs
benches/json.rs
benches/mp4.rs
src/byte.rs
src/char.rs
src/combinator.rs
src/lib.rs
src/primitives.rs
src/range.rs
src/regex.rs
src/state.rs
test.rs
tests/buffered_stream.rs
tests/ini.rs
tests/readme.rs

This contains the current breaking changes I am planning to do for 3.0. More changes that are yet to be implemented are tracked in https://github.com/Marwes/combine/milestone/4.
Before this is merged I'd expect a few alpha/beta releases to be released on crates.io as well.

Tracking PR for 3.0

---

src/combinator.rs

The `not_followed_by` doc says that it never consumes any input,
however it does if parser succeeds.
The implementation was missing a `try` before which made the parser preserve the `Consumed` status if `P` consumed input before failing. This is because `try` only makes errors look like they haven't consumed any input and at the point of the inner `try` the parse status is still `Ok`.
See http://hackage.haskell.org/package/parsec-3.1.11/docs/src/Text.Parsec.Combinator.html#notFollowedBy
Closes #117

fix: not_followed_by now does not consume any input

---

src/byte.rs
src/char.rs
src/combinator.rs
src/primitives.rs

I'm not sure if these impls were purposefully left out for some reason, but they make some of my parsers much more ergonomic.

Implement Copy for more types

---

src/easy.rs
src/lib.rs
tests/parser_macro.rs

This allows items to be put into `parser!` and should make error
messages clearer.
BREAKING CHANGE
`parser!` no longer works when the resulting parser contains borrows to
stack allocated values. This was necessary to support the improvements
and is also consistent with how returning `impl Parser` works.

feat: Accept arbitrary blocks in the parser! macro

---

README.md
src/error.rs
src/lib.rs
src/parser/item.rs
src/parser/mod.rs
src/parser/range.rs
src/stream/buffered.rs
src/stream/easy.rs

This is a great library and I am really excited about the 3.0 release! There are a few typos in the docs, however. These are the ones I caught by running `aspell` on the `.rs` files and the `README`.

Fix a few typos in the docs

---

src/parser/char.rs

In a project I'm working on, I naively assumed that `combine::parser::char::newline` parsed any unicode newline, including LF and CRLF, which led to a bug that was a real pain to solve. I've made the docs slightly more clear in the hopes of helping future users avoid the mistake that I made.

Add specific characters to docs in combine::parser::char

---

src/parser/range.rs
tests/async.rs

This modifies `uncons_range` to uncons a number of chars instead of a number of
bytes for `str`s.
The reasons for this change is that `uncons_range` was was causing `UnexpectedParse` errors with functions like `take_until_range` when Unicode characters were present in the string being parsed.
I worry a bit about the performance impact for calls to `uncons_range` with large `size` arguments, but I can't think of a better way to fix the issue, besides maybe a feature flag to opt in/out of unicode support.

Support Unicode characters in uncons_range for strs

---

CHANGELOG.md
Cargo.toml
release.sh
release.toml
src/lib.rs
src/parser/combinator.rs
src/parser/range.rs
tests/parser.rs

I checked all other definitions of `parse_partial` as well and all other seem fine (does not need to be parse_mode instead) as they do not invoke another parser recursively
cc #168

fix: Propagate the ParseMode in range::recognize

---

README.md

The badges will still all display on one line but now they are much easier to see in code.

Fix docs link and reformat badges

---

README.md

Version 3 already has a link through other link that goes to the most recent version

doc: Restore the doc link to version 2

---

src/lib.rs
src/parser/choice.rs
src/parser/combinator.rs
src/parser/mod.rs
src/parser/range.rs
src/parser/repeat.rs
tests/async.rs
tests/buffered_stream.rs
tests/parser.rs

Since `try` is reserved in Rust 2018, this adds a new function, `attempt`, that is equivalent to `try`. 
This PR is separated into 3 commits:
1. Adds the alias + docs
2. Deprecates `try`
3. Refactors all internal usages of `try` to `attempt`.

Refactors try into attempt

---

src/parser/combinator.rs

https://docs.rs/combine/3.6.0/combine/parser/combinator/struct.Try.html
Because `/**` comments are seen by rustdoc as documentation (TIL 😅), this todo was included in the build. 
This changes it to a regular comment that won't be included.

Do not show the TODO on docs.rs

---

src/lib.rs
src/parser/combinator.rs
src/parser/sequence.rs

fix: Allow clippy to run on stable rust

---

src/parser/byte.rs

To be honest, "byteacter" sounds pretty cool, but I'm assuming this is an error in documentation :smile:

Fix documentation errors caused by char->byte text replacement

---

src/error.rs

1.
- `easy::Errors` is EOI if any of it's added `StreamError`s is EOI
while
- `UnexpectedParse`/`StringStreamError` is EOI if the last added `StreamError` is EOI
2.
- `StringStreamError::into_other()` propagates EOI while `UnexpectedParse` stringifies it.
50% chance that I fixed 1. the corrent way :smile:

Fix two inconsisties regarding EOI

---

Cargo.lock
Cargo.toml
src/parser/byte.rs
src/parser/char.rs
src/parser/range.rs

* `take_fn` simplifies the use of searchers/parsers outside of combine
(for example `memchr` or `jetscii`)
* `take_until_bytes` builds on `take_fn` and uses `memchr` to quickly
find the next instance of a byte string.

feat: Add take_fn and take_until_bytes

---

src/parser/byte.rs
src/stream/mod.rs

feat: Allow ReadStream parsers to use &[u8] in errors

---

Cargo.lock
Cargo.toml
src/lib.rs
src/parser/sequence.rs

Replaces an old and unnecessary crate with the corresponding intrinsic that now exists in the language.

Replace unreachable crate with intrinsic

---

src/parser/choice.rs

Enables forms such as:
```rust
dispatch!(foo
"one_value" => parser_for_one_value(),
foo if foo[0] == "x" => parser_when_starting_with_x(),
_ => unexpected_any("whatever"));
```

extend dispatch! macro to work with match guards

---

benches/json.rs
src/error.rs
src/lib.rs
src/parser/byte.rs
src/parser/choice.rs
src/parser/combinator.rs
src/parser/error.rs
src/parser/function.rs
src/parser/mod.rs
src/parser/range.rs
src/parser/regex.rs
src/parser/repeat.rs
src/parser/sequence.rs
src/parser/token.rs
src/stream/mod.rs

This more accurately explains what these cases mean. Either a parser has
committed to its parse, so if it fails it should not attempt other
parsers or it just `peek`ed on its input and it is ok to attempt another
one.
`Consumed` and `Empty` were only accurate in what they did in simple
cases but as soon as `attempt` or a partial input failed they would not
be true any more. Also this is just a better explanation of how other
parsers should act when a parser returns one of these.
BREAKING CHANGE
Rename any use of `Consumed` to `Commit` and `Empty` to `Peek`

feat: Rename Consumed to Commit and Empty to Peek

---

README.md

Copy/pasting the example from the readme yields this error:
```
error[E0432]: unresolved import `combine::char`
--> src/main.rs:3:14
|
3 | use combine::char::{letter, space};
|              ^^^^ could not find `char` in `combine`
```

fix char module name in example

---

src/parser/repeat.rs

In addition to the type, the wording of this documentation is not entirely clear to a newcomer.
``(`attempt` can be used to make it look like it has not committed any input)`` and ``// `attempt` must be used if the `end` should consume input before failing`` are phrased in a complicated way.
How about ``(`attempt` can be used to continue skipping even if `end` has committed input)`` and ``// `attempt` must be used because the `end` will commit to `TA` before failing, but we want to continue skipping``?

Fix typo and test in docs

---

src/parser/repeat.rs

I noticed this second doc test that had a dangling bracket.
From a quick look it seems that generally the doc tests are formatted correctly, so this and `skip_until` were exceptions.

Fix formatting of doc test

---

examples/async.rs
examples/date.rs
examples/ini.rs
src/lib.rs

* allow not using 'matches!()' for now due to constraint to Rust 1.40
* run with `cargo clippy --examples` to catch more issues and fix them

Fix clippy for good

---

Cargo.toml
src/lib.rs
src/parser/combinator.rs
src/parser/mod.rs
src/stream/buf_reader.rs
src/stream/decoder.rs
src/stream/mod.rs

This crate have used a bunch of `#[cfg_attr(docsrs, doc(cfg(feature = "...")))]` annotations,
but it had 3 problems:
- Not all `cfg`-ed had one
- The crate didn't enable `feature(doc_cfg)` which made it's docs unbuildable with `--cfg docsrs` (this also caused problems when building docs of crates which depend on this crate)
- docs.rs setting were missing `--cfg docsrs`, so it didn't include `supported on crate feature="..." only` things
This PR fixes those problems.

fix doc(cfg) annotations

---

src/parser/byte.rs
src/parser/mod.rs
src/parser/range.rs
src/stream/decoder.rs
src/stream/easy.rs
src/stream/mod.rs

This pull request mainly involves modifying links in some document comments.
* [cargo-doc](https://doc.rust-lang.org/cargo/commands/cargo-doc.html) and [cargo-deadlinks](https://crates.io/crates/cargo-deadlinks) are used for verification.
* Links are specified by name for the corrected parts. Reference: [The Rustdoc Book](https://doc.rust-lang.org/rustdoc/linking-to-items-by-name.html)
In addition, there are some corrections that I noticed while modifying the links.
The list them is below. If you have any suggestions, please let me know.
* `src/parser/mod.rs` >
* `Parser`, `left`, `right` are enclosed in square brackets: I think that linking like this can be not only convenient but also safe since they can be verified that the path is correct.
* `partial_then` to `then_partial`
* …

Fix and add some document links

---

Cargo.lock
Cargo.toml

tokio 0.2 depends on pin-project-lite 0.1, but everything else (futures-util, tokio 0.3, tokio 1.0) depends on pin-project-lite 0.2.

Update pin-project-lite to 0.2

---

.travis.yml
src/lib.rs
src/parser/mod.rs
src/parser/repeat.rs
src/parser/sequence.rs
src/stream/mod.rs
tests/async.rs
travis.sh

This works mostly the same as the regular `decode` function but it
can be plugged into both `decode` and `decode_eof` it will work as long
as the `eof` variant marks the input as non-partial.
Also ensures that unexpected end of inputs always get returned so that
we can detect them at the real end of input and return `None`.
The reqular `decode` function ended up still working as long as the
stream was always reported as partial as the parsers would endeavour
to return unexpected end of input in those cases.

feat: Add decode_tokio

---

Cargo.toml
src/parser/sequence.rs
src/stream/buf_reader.rs
src/stream/mod.rs

2 changes:
1. update `poll_extend_buf` to actually preinitialize the bytes as suggested by comment
2. add an assertion to prevent ever reading uninit bytes out of a slice if other arithmetic errors occur
3. add `// SAFETY: ...` comments to a number of unsafe blocks

Fix a couple instances of potential UB

---

Cargo.toml
src/stream/buf_reader.rs

tokio-util now exposes the poll_read_buf function so we can use it
directly instead of copying it for tokio 1.0 at least

refactor: Remove some unsafe blocks in buf_reader

---

src/parser/char.rs
src/stream/buf_reader.rs

```
warning: use of deprecated trait `std::ascii::AsciiExt`: use inherent methods instead
--> src/parser/char.rs:274:17
|
5 | use std::ascii::AsciiExt;
|                 ^^^^^^^^
|
= note: `#[warn(deprecated)]` on by default
warning: 1 warning emitted
```
```
warning: unused import: `mem::MaybeUninit`
--> ~/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/combine-4.6.1/src/stream/buf_reader.rs:9:11
|
9 | use std::{mem::MaybeUninit, pin::Pin};
|           ^^^^^^^^^^^^^^^^
|
= note: `#[warn(unused_imports)]` on by default
```

fix: warning

---

src/lib.rs
src/stream/easy.rs

When reviewing cargo moving fron `toml-rs` (hand-rolled parser) to
`toml_edit` (`combine`-based parser), one piece of feedback was about
only wanting tokens quoted and not textual descriptions.  It looks like
`combine` tracks all of the needed information and just a re-formatting
of the output is needed.
Fixes #334

fix(easy): Only back-quote parser tokens

---

src/stream/mod.rs

It appears that the feature flag has been changed from `std` to `alloc` some time in the past. However, the corresponding documentation attribute has been left unchanged.
Now one can (according to the docs) actually use `combine` with iterators on microcontrollers where you have an allocator available! 😉

Update feature-flag in documentation

---

src/parser/sequence.rs

refactor: Extract less-generic code from sequence's add_errors (-5%)

---

Cargo.toml

This leads to (possibly) different set of selected features when building some crates. https://github.com/BurntSushi/memchr/commit/8efd67fcc412445d6978cf35761ab81ed2d6e6fe

memchr: use non deprecated feature `std` instead of `use_std`

---

.github/workflows/rust.yml
benches/http.rs
benches/json.rs
examples/async.rs
examples/date.rs
examples/ini.rs
src/error.rs
src/lib.rs
src/parser/byte.rs
src/parser/char.rs
src/parser/combinator.rs
src/parser/function.rs
src/parser/sequence.rs
src/stream/mod.rs
src/stream/position.rs
tests/async.rs

Due to an old Rust bug, rust-lang/rust#24159, many parsers included an extraneous trait bound for Input::Error as a workaround. That bug has been closed since February 2021, and the workaround is no longer needed.
There are a few places I did NOT remove `Input::Error` bound from the `where` clause, which would be nice to eliminate but I think may be required:
- stream/position.rs requires it to specify the `StreamError` associated type in the `Positioned` and `StreamOnce` implementations.
- stream/easy.rs similarly requires it to specify `StreamError` in the docs example
- parser/combinator.rs requires `Into<...::StreamError>` for the error generic in its `AndThen` struct
- src/lib.rs has similar awkward boilerplate for `...:StreamError: From<ParseIntError>` in its docs examples

Remove extraneous Input::Error trait bounds

---

.github/workflows/rust.yml
Cargo.lock

Newer versions of memchr requires this more recent version of rust, so to keep things simple we just keep pace here (the minimum rust version is just to guard against using too recent features of rust)

chore: Update CI to run against rust 1.61

---

src/lib.rs

Return position impl was enabled in Rust 1.26 in May 10, 2018 [1].
1- https://blog.rust-lang.org/2018/05/10/Rust-1.26.html#impl-trait

docs: remove mention to nightly

---

CHANGELOG.md

Fixed a typo:  
- In `CHANGELOG.md`, corrected `depreceated` to `deprecated`.

typo fix CHANGELOG.md
